alyve/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/urls.py
from django.urls import path

from . import views
from blog.feeds import LatestArticlesFeed, UnvalidedCommentsFeed, ValidedCommentsFeed

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('article/<slug:slug>', views.ArticleView.as_view(), name='article'),
    path('page/<slug:slug>', views.PageView.as_view(), name='page'),
    path('category/<slug:slug>', views.CategoryView.as_view(), name='category'),
    path('feeds/articles', LatestArticlesFeed()),
    path('feeds/unvalided-comments', UnvalidedCommentsFeed()),
    path('feeds/comments', ValidedCommentsFeed()),
    path('article/<slug:slug>/comment', views.add_comment, name='add_comment'),
]

blog/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext as _
from django.db.models.signals import pre_save
from django.dispatch import receiver

from slugify import slugify

SOCIAL_CHOICES = (
    ('LINKED_IN', 'Linked In'),
    ('INSTAGRAM', 'Instagram'),
    ('RSS_FLUX', 'Flux RSS'),
    ('FACEBOOK', 'Facebook'),
    ('GITHUB', 'Github'),
    ('BITBUCKET', 'Bitbucket'),
    ('GOOGLE_PLUS', 'Google+'),
    ('YOUTUBE', 'Youtube'),
    ('MASTODON', 'Mastodon'),
    ('DIASPORA', 'Diaspora'),
    ('PEERTUBE', 'Peertube'),
    ('PATREON', 'Patreon'),
    ('DISCORD', 'Discord')
)

class Blog(models.Model):
    name = models.CharField('Nom', max_length=255)
    description = models.CharField('Description', max_length=500, blank=True, null=True)
    cover = models.ImageField('Image de couverture', upload_to='blog/', blank=True, null=True)
    sidebar_title = models.CharField('Barre latérale', max_length=30, blank=True, null=True)
    sidebar_picture = models.ImageField('Avatar', upload_to='blog/', blank=True, null=True)
    sidebar_description = models.TextField('Description dans la sidebar', max_length=250, blank=True, null=True)

class Media(models.Model):
    file = models.FileField(upload_to='media/')
    title = models.CharField('Nom', max_length=100, blank=True, null=True)

class Page(models.Model):
    name = models.CharField('Nom', max_length=100)
    slug = models.SlugField('Lien d\'accès', max_length=100, unique=True)
    content = models.TextField('Contenu')
    displayed = models.BooleanField('Affiché dans le menu', default=True)
    cover = models.ImageField('Image de couverture', upload_to='pages/', blank=True, null=True)

class Comment(models.Model):
    username = models.CharField('Nom d\'utilisateur', max_length=25)
    publication_date = models.DateTimeField('Date de publication')
    valided = models.BooleanField('Validé', default=False)
    content = models.TextField('Contenu')
    
    article = models.ForeignKey(
        'Article',
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = _('Commentaire')
        verbose_name_plural = _('Commentaires')

class Article(models.Model):
    title = models.CharField('Titre', max_length=200)
    slug = models.SlugField('Lien d\'accès', max_length=100, unique=True)
    content = models.TextField('Contenu')
    publication_date = models.DateTimeField('Date de publication')
    update_date = models.DateTimeField('Date de mise à jour', blank=True, null=True)
    published = models.BooleanField('Publié', default=False)
    cover = models.ImageField('Image de couverture', upload_to='covers/', blank=True, null=True)
    hide_image = models.NullBooleanField('Cacher les images', default=False)
    disclaimer = models.TextField('Disclaimer', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    def comments_count(self):
        return Comment.objects.filter(article=self.id).count()

    def unvalided_comments(self):
        return Comment.objects.filter(article=self.id, valided=False)
    
    def unvalided_comments_count(self):
        return Comment.objects.filter(article=self.id, valided=False).count()

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField('Nom', max_length=60)
    slug = models.SlugField('Lien d\'accès', max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Catégorie')
        verbose_name_plural = _('Catégories')

class Question(models.Model):
    question = models.CharField('Question', max_length=100)
    answer = models.CharField('Réponse', max_length=2)

class Link(models.Model):
    sort = models.IntegerField('Ordre', default="5")
    link = models.URLField('Lien')
    shortcut = models.CharField('Titre', max_length=60)
    
    def __str__(self):
        return self.shortcut

    class Meta:
        verbose_name = _('Lien')
        verbose_name_plural = _('Liens')

class Social(models.Model):
    sort = models.IntegerField('Ordre', default="5")
    link = models.URLField('Lien')
    network = models.CharField('Réseau', choices=SOCIAL_CHOICES, max_length=16, blank=True, null=True)
    shortcut = models.CharField('Titre', max_length=60)
    sidebar = models.BooleanField('Affiché dans la sidebar', default=False)

    def __str__(self):
        return self.shortcut


@receiver(pre_save, sender=Page)
def cb_page_slug(sender, instance, **kwargs):
    if instance.id is None:
        instance.slug = slugify(instance.name)

@receiver(pre_save, sender=Article)
def cb_article_slug(sender, instance, **kwargs):
    if instance.id is None:
        instance.slug = slugify(instance.title)

@receiver(pre_save, sender=Category)
def cb_category_slug(sender, instance, **kwargs):
    if instance.id is None:
        instance.slug = slugify(instance.name)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages

from .models import Article, Comment, Category, Blog, Page, Question, Link, Social

from random import randint 

class IndexView(generic.ListView):
    model = Article
    template_name = 'index.html'
    pagined_by = 9

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        articles = Article.objects.filter(published=True).order_by('-publication_date')
        paginator = Paginator(articles, self.pagined_by)

        page = self.request.GET.get('page')

        try:
            articles_page = paginator.page(page)
        except PageNotAnInteger:
            articles_page = paginator.page(1)
        except EmptyPage:
            articles_page = paginator.page(paginator.num_pages)

        context['articles'] = articles_page
        context['blog'] = Blog.objects.get(pk=1)
        context['pages'] = Page.objects.filter(displayed=True)
        context['categories'] = Category.objects.all()
        context['links'] = Link.objects.order_by('sort')
        context['social'] = Social.objects.order_by('sort')
        return context

class CategoryView(generic.ListView):
    
    template_name = 'category.html'
    pagined_by = 6

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Article.objects.filter(published=True, category=self.category).order_by('-publication_date')

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        
        paginator = Paginator(self.get_queryset(), self.pagined_by)
        page = self.request.GET.get('page')

        try:
            articles_page = paginator.page(page)
        except PageNotAnInteger:
            articles_page = paginator.page(1)
        except EmptyPage:
            articles_page = paginator.page(paginator.num_pages)

        context['blog'] = Blog.objects.get(pk=1)
        context['pages'] = Page.objects.filter(displayed=True)
        context['categories'] = Category.objects.all()
        context['links'] = Link.objects.order_by('sort')
        context['social'] = Social.objects.order_by('sort')
        context['category'] = self.category
        context['articles'] = articles_page
        del context['article_list']
        return context

class ArticleView(generic.DetailView):
    model = Article
    template_name = 'article.html'
    
    def get_context_data(self, **kwargs):
        context = super(ArticleView, self).get_context_data(**kwargs)
        
        context['blog'] = Blog.objects.get(pk=1)
        context['pages'] = Page.objects.filter(displayed=True)
        context['comments'] = Comment.objects.filter(article=self.object.id, valided=True).order_by('-pk')
        context['categories'] = Category.objects.all()
        context['links'] = Link.objects.order_by('sort')
        context['social'] = Social.objects.order_by('sort')

        # get a random question for comment something
        question_count = Question.objects.count()
        if question_count > 0:
            index = randint(0, question_count-1)
            if index is not None:
                context['question'] = Question.objects.all()[index]
        return context

class PageView(generic.DetailView):
    model = Page
    template_name = 'page.html'
    
    def get_context_data(self, **kwargs):
        context = super(PageView, self).get_context_data(**kwargs)
        context['blog'] = Blog.objects.get(pk=1)
        context['pages'] = Page.objects.filter(displayed=True)
        context['categories'] = Category.objects.all()
        context['links'] = Link.objects.order_by('sort')
        context['social'] = Social.objects.order_by('sort')
        return context

def add_comment(request, slug):
    if request.method == 'POST':
        username = request.POST.get('comment_username', None)
        website = request.POST.get('comment_website', None)
        content = request.POST.get('comment_comment', None)
        answer = request.POST.get('comment_answer', None)
        question_id = int(request.POST.get('comment_question', None))

        if username and content and answer and question_id:
            question = Question.objects.get(pk=question_id)
            if answer == question.answer:
                article = Article.objects.get(slug=slug)
                comment = Comment(username=username, content=content, publication_date=timezone.now(), article=article)
                comment.save()
                messages.add_message(request, messages.INFO, 'COMMENT_ADDED')
            else:
                messages.add_message(request, messages.INFO, 'WRONG_ANSWER')
        else:
            messages.add_message(request, messages.INFO, 'BAD_FORM')

    return redirect(reverse('blog:article', args=[slug]))

blog/templates/article.html
{% extends 'template.html' %}
{% load markdown_deux_tags %}
{% load static %}

{% block title %} - {{ article.title }}{% endblock %}

{% block seo %}
<meta property="og:title" content="{{ article.title }}" />
<meta property="og:type" content="article" />
<meta property="og:url" content="{{ request.build_absolute_uri }}" />
{% if article.cover %}
<meta property="og:image" content="{% if request.is_secure %}https{% else %}http{% endif %}://{{ request.get_host }}/uploads/{{ article.cover }}" />
{% endif %}
<meta property="og:description" content="{{ article.content | markdown | striptags | truncatewords:50 }}" />
{% endblock %}

{% block content %}
{% if messages %}
<div class="column is-8 is-offset-2">
  {% for message in messages %}
    {% if message|stringformat:"s" == "COMMENT_ADDED" %}
      <div class="notification is-success">
          <strong>Votre commentaire a été ajouté !</strong> Il sera validé par l'administrateur·rice.
        </div>
    {% elif message|stringformat:"s" == "WRONG_ANSWER" %}
      <div class="notification is-warning" role="alert">
        <strong>Mince!</strong> Vous n'avez pas donner la bonne réponse à la question.
      </div>
    {% elif message|stringformat:"s" == "BAD_FORM" %}
      <div class="notification is-danger" role="alert">
        <strong>Mince!</strong> Vous n'avez pas totalement rempli le formulaire.
    </div>
    {% endif %}
  {% endfor %}
</div>
{% endif %}

<section class="articles">
  <div class="column is-8 is-offset-2">
    {% if article %}
    <div class="card article-view">
      {% if article.cover %}
      <div class="card-header">
        <figure>
          <img src="{{ article.cover.url }}">
        </figure>
      </div>
      {% endif %}
      <div class="card-content">
        <div class="media">
          <div class="media-content has-text-centered">
            <p class="title article-title">{{ article.title }}</p>
            <p class="subtitle has-text-centered">
                Écrit par {{ article.author.username }} le {{ article.publication_date | date }} dans <a href="{% url 'blog:category' article.category.slug %}">{{ article.category.name }}</a>
              </p>
          </div>
        </div>
        <div class="content article-body {% if article.hide_image %}hidden{% endif %}">
          {{ article.content|markdown }}
        </div>
      </div>
      {% endif %}
    </div>
    <hr>
    <section class="content">
      <h3>Partager cet article sur les médias sociaux</h3>
      <div class="container">
        <div class="">
          <div 
            class="mastodon-share-button"
            data-target="https://framapiaf.org"
            data-name="Framapiaf"
            data-buttonstyle="button is-primary is-rounded"
            data-text="&nbsp;Share on Mastodon"
          >
            &nbsp;<button class="button is-info is-rounded" href="javascript:;" onclick="window.open('https://share.diasporafoundation.org/?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title),'das','location=no,links=no,scrollbars=no,toolbar=no,width=620,height=550'); return false;" rel="nofollow" target="_blank">
              <i class="fa fa-diaspora" aria-hidden="true"></i>&nbsp;Share on Diaspora*
            </button>
          </div>
        </div>

        </div>
      </div>

    </section>
    <hr>
    <section class="column is-8 is-offset-2 content">
      <h3>Écrire un commentaire</h3>
      <form action="{% url 'blog:add_comment' article.slug %}" method="post">
        {% csrf_token %}
        <div class="field">
          <label class="label">
            Nom d'utilisateur·rice
          </label>
          <div class="control">
            <input
              class="input" 
              type="text" 
              placeholter="Votre nom d'utilisateur·rice"
              name="comment_username"
            />
          </div>
        </div>

        <div class="field">
          <label class="label">
            Répondez à la question: {{ question.question }}
          </label>
          <div class="control">
            <input
              class="input"
              type="text"
              name="comment_answer"
              placeholder="42"
            />
          </div>
        </div>

        <div class="field">
          <label class="label">
            Entrez votre commentaire
          </label>
          <textarea name="comment_comment" class="textarea"></textarea>
        </div>

        <input type="hidden" name="comment_question" value="{{ question.id }}">

        <button type="submit" class="button is-primary is-pulled-right">Envoyer mon commentaire</button>
      </form>
      <hr>
      {% if comments %}
      <h3>Commentaire(s) lié(s) à l'article</h3>
      {% for comment in comments %}
      <article class="media">
          <div class="media-content">
            <div class="content comment">
              <p>
                <strong>{{ comment.username }}</strong> <small>{{ comment.publication_date | date }}</small>
                <br>
                {{ comment.content | markdown }}
              </p>
            </div>
          </div>
        </article>
      {% endfor %}
      {% endif %}
    </section>
</section>

{% if article.hide_image %}
<div class="is-invisible" id="article-disclaimer">
  {{ article.disclaimer }}
</div>
{% endif %}

{% endblock %}

blog/templates/category.html
{% extends 'template.html' %}
{% load markdown_deux_tags %}

{% block title %} - {{ category.name }}{% endblock %}

{% block header %}
<h3 class="maintitle">{{ category.name }}</h3>
<i class="fa fa-list-alt" aria-hidden="true"></i> <a href="#comments">{{ articles.count }} article{% if articles.count > 1 %}s{% endif %}</a>
{% endblock %}

{% block content %}
<div class="container">

    {% if articles %}
    {% include "includes/pagination.html" %}
    <section class="articles">
        <div class="columns">
            {% for article in articles %}
            <div class="column is-4">
                <section class="card article">
                    {% if article.cover %}
                    <div class="card-image article-image">
                        <figure class="image">
                            <img src="{{ article.cover.url }}" alt="{{ article.name }} cover">
                        </figure>
                    </div>
                    {% endif %}
                    <div class="card-content">
                        <p class="title has-text-centered">
                            <a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a>
                        </p>
                        <p class="subtitle has-text-centered">
                            Écrit par {{ article.author.username }} le {{ article.publication_date | date }} dans <a href="{% url 'blog:category' article.category.slug %}">{{ article.category.name }}</a>
                        </p>
                        {{ article.content | markdown | truncatewords:50 }}
                    </div>
                </section>
            </div>
            {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class="columns">
            {% endif %}
            {% endfor %}
        </div>
    </section>
    {% include "includes/pagination.html" %}
    {% else %}
    <h4 class="title">Oops! Il n'y a pas encore d'article ici.</h4>
    {% endif %}
</div>
{% endblock %}

blog/templates/index.html
{% extends 'template.html' %}
{% load markdown_deux_tags %}

{% block content %}
  {% include "includes/pagination.html" %}
  {% if articles %}
    <section class="articles">
      <div class="columns">
      {% for article in articles %}
        <div class="column is-4">
        <section class="card article">
          {% if article.cover %}
          <div class="card-image article-image">
            <figure class="image">
              <img src="{{ article.cover.url }}" alt="{{ article.name }} cover">
            </figure>
          </div>
          {% endif %}
          <div class="card-content">
            <p class="title has-text-centered">
              <a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a>
            </p>
            <p class="subtitle has-text-centered">
              Écrit par {{ article.author.username }} le {{ article.publication_date | date }} dans <a href="{% url 'blog:category' article.category.slug %}">{{ article.category.name }}</a>
            </p>
            {{ article.content | markdown | truncatewords:50 }}
          </div>
        </section>
      </div>
      {% if forloop.counter|divisibleby:3 %}
      </div>
      <div class="columns">
      {% endif %}
      {% endfor %}
    </div>
    </section>
  {% endif %}
  {% include "includes/pagination.html" %}
{% endblock %}

blog/templates/page.html
{% extends 'template.html' %}
{% load markdown_deux_tags %}

{% block title %} - {{ page.name }}{% endblock %}

{% block hero-style %}
{% if page.cover %}
style="background-image: url('/uploads/{{ page.cover }}');"
{% else %}
style="background-image: url('/uploads/{{ blog.cover }}');"
{% endif %}
{% endblock %}

{% block header %}
<h3 class="maintitle">{{ page.name }}</h3>
{% endblock %}
}
{% block content %}
<section class="articles">
    <div class="column is-8 is-offset-2">
        {% if page %}
        <div class="card article">
            <div class="card-content">
                <div class="media">
                    <div class="media-content has-text-centered">
                        <p class="title article-title">{{ page.name }}</p>
                    </div>
                </div>
                <div class="content article-body">
                    {{ page.content|markdown }}
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

blog/templates/template.html
{% load static %}
{% load markdown_deux_tags %}
<!doctype html>
<html lang="fr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{{ blog.name }}{% block title %}{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/bulma.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/alertify/alertify.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/alertify/themes/default.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/fork-awesome.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}" />
  <link rel="icon" href="{% static 'blog/img/favicon.png' %}" />

  {% for s in social %}
  {% if s.network == 'RSS_FLUX' %}
  <link href="{{ s.link }}" rel="alternate" title="Rss feed" type="application/rss+xml">
  {% else %}
  {% endif %}

  {% endfor %}

  {% block seo %}
  <meta property="og:title" content="{{ blog.name }}" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="{{ request.build_absolute_uri }}" />
  <meta property="og:image" content="{{ request.build_absolute_uri }}uploads/{{ blog.sidebar_picture }}" />
  {% endblock %}
</head>

<body class="has-navbar-fixed-top">
    <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
      <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'blog:index' %}">
              {% if blog.cover %}
              <img height="28px" src="{{ blog.cover.url }}" alt="{{ blog.name }}">
              {% endif %}
            </a>
            <span class="navbar-burger burger" data-target="navbarMenu">
                <span></span>
                <span></span>
                <span></span>
            </span>
          </div>
        <div id="navbarMenu" class="navbar-menu">
            <div class="navbar-start">
              {% if categories %}
              {% for category in categories %}
              <a class="navbar-item navbar-category" href="{% url 'blog:category' category.slug %}">{{ category.name }}</a>
              {% endfor %}
              {% endif %}
            </div>
          
            <div class="navbar-end">
              {% if social %}
              {% for s in social %}
              {% if s.sidebar %}
                <a class="navbar-item" href="{{ s.link }}" target="_blank">
                    {% if s.network == 'RSS_FLUX' %}
                    <i class="fa fa-rss" aria-hidden="true"></i>
                    {% elif s.network == 'GITHUB' %}
                    <i class="fa fa-github" aria-hidden="true"></i>
                    {% elif s.network == 'LINKED_IN' %}
                    <i class="fa fa-linkedin" aria-hidden="true"></i>
                    {% elif s.network == 'INSTAGRAM' %}
                    <i class="fa fa-instagram" aria-hidden="true"></i>
                    {% elif s.network == 'FACEBOOK' %}
                    <i class="fa fa-facebook-square" aria-hidden="true"></i>
                    {% elif s.network == 'BITBUCKET' %}
                    <i class="fa fa-bitbucket" aria-hidden="true"></i>
                    {% elif s.network == 'GOOGLE_PLUS' %}
                    <i class="fa fa-google-plus" aria-hidden="true"></i>
                    {% elif s.network == 'YOUTUBE' %}
                    <i class="fa fa-youtube-play" aria-hidden="true"></i>
                    {% elif s.network == 'MASTODON' %}
                    <i class="fa fa-mastodon" aria-hidden="true"></i>
                    {% elif s.network == 'PEERTUBE' %}
                    <i class="fa fa-peertube" aria-hidden="true"></i>
                    {% elif s.network == 'DIASPORA' %}
                    <i class="fa fa-diaspora" aria-hidden="true"></i>
                    {% endif %}
                  </a>
                {% endif %}
                {% endfor %}
                {% endif %}

                {% if pages %}
                {% for page in pages %}
                <a class="navbar-item navbar-page" href="{% url 'blog:page' page.slug %}">
                  {{ page.name }}
                </a>
                {% endfor %}
                {% endif %}
            </div>
          </div>

      </div>
    </nav>
  <div class="container">
    <section class="hero">
      <div class="hero-body">
        <div class="container">
          <img class="is-pulled-left blog__avatar" src="{{ blog.sidebar_picture.url }}">
          <h1 class="title">
            {{ blog.name }}
          </h1>
          <h2 class="subtitle">
            {{ blog.description }}
          </h2>
        </div>
      </div>
  </section>

  </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </div>

  <footer class="footer">
    <div class="container">
      <div class="columns">
        <div class="column">
          {% if social %}
          <span class="has-text-weight-bold is-uppercase">Média sociaux</span>
          <ul class="list-unstyled">
            {% for s in social %}
            <li><a href="{{ s.link }}">{{ s.shortcut }}</a></li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="column">
          {% if links %}
          <span class="has-text-weight-bold is-uppercase">Liens</span>
          <ul class="list-unstyled">
            {% for link in links %}
            <li><a href="{{ link.link }}">{{ link.shortcut }}</a></li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <div class="column has-text-right">
          <p>Created by Alyve with <span class="primary">❤</span>.</br>
            © Alyve 2017 - 2018</p>
        </div>
      </div>
    </div>
  </footer>

  {% include "includes/mastodon.html" %}
  <script src="{% static 'blog/js/alertify.min.js' %}"></script>
  <script src="{% static 'blog/js/blog.js' %}"></script>
  <script src="{% static 'blog/js/mastodon.js' %}"></script>
</body>

</html>